name: clean_architecture_app
description: Posts App with clean architecture

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get_it: ^7.2.0
  flutter_bloc: ^8.0.1
  dartz: ^0.10.1
  internet_connection_checker: ^0.0.1+3
  http: ^0.13.4
  shared_preferences: ^2.0.15
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
